### ISSUE TITLE
json in the requirements.txt of pip throws err

### ISSUE THREAD

**Issue by maximlomans** [GoSecure/gophish-cli#5]
throws error : Could not find a ... 
sudo pip3 install -r requirements.txt --user
Collecting prettytable (from -r requirements.txt (line 1))
  Using cached prettytable-0.7.2.tar.bz2
Requirement already satisfied: paramiko in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2))
Collecting json (from -r requirements.txt (line 3))
  Could not find a version that satisfies the requirement json (from -r requirements.txt (line 3)) (from versions: )
No matching distribution found for json (from -r requirements.txt (line 3))
---------------. 
Could not find a version that satisfies the requirement dateutil also erred 
turns out there's 
dateutils 0.6.6 
 bdateutil 0.1
py-dateutil 2.2
 etc etc 
 Is it necessary to the install ? also i had to cp the requirements txt file into the api-client-python dir since it kept complaining about not finding it. I looked in the requirements and json is listed yet a google search showed it as an embedded module of pip and that it wasn't needed . 
on the otherhand i found a module called  ' simplejson 3.13.2'  .
I just though i'd let you know in case for some reason it didn't show up as such in your env.
i hate it when console starts spitting red colored text , i'm the squeamish type  :  \
thanks for sharing

**Comment by martindube** [comment]
Thanks for opening the issue. There were 2 unnecessary dependencies. The default json and dateutil libraries in Python3 are sufficient.

Regarding the issue with `api-client-python`, I can't reproduce it. If you `git clone --recursive` the project, the folder `api-client-python` should have a `requirements.txt`
